# Generated by Django 2.2.4 on 2019-08-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.TextField()),
                ('role', models.TextField()),
                ('alive', models.BooleanField()),
                ('name', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('state', models.TextField()),
            ],
        ),
    ]
