# Generated by Django 2.2.4 on 2019-08-29 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.TextField()),
                ('role', models.TextField()),
                ('alive', models.BooleanField()),
                ('name', models.TextField()),
                ('color', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Session')),
            ],
        ),
    ]
